modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"

[[mods]]
modId="apotheosis_strip"
version="1.0.0"
displayName="神化-剥离"
authors="Xiaoyu_2009"
displayURL="https://space.bilibili.com/506597031"
description='''
本模组将神化模组里面的一些内容剥离出来了
'''

[[dependencies.apotheosis_strip]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.apotheosis_strip]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH" 